# .air.toml
# Config file for Air - https://github.com/air-verse/air
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/api/main.go"
  bin = "./tmp/server"
  full_bin = "APP_ENV=development ./tmp/server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  include_dir = []
  exclude_file = []
  log = "air.log"
  delay = 1000 # ms
  stop_on_error = true
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
